name: Recent Activity

on:
  schedule:
    - cron: '*/30 * * * *' # Every 30 minutes
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Recent Activity
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Normalize activity markers
        run: |
          sed -i 's/<!-- START_SECTION:activity -->/<!--START_SECTION:activity-->/g' README.md
          sed -i 's/<!-- END_SECTION:activity -->/<!--END_SECTION:activity-->/g' README.md
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
